-- 1. Create the favorites table
create table favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  item_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, item_id)
);

-- 2. Enable Row Level Security (RLS)
alter table favorites enable row level security;

-- 3. Create Policies (Security Rules)
-- Allow users to add their own favorites
create policy "Users can insert their own favorites"
  on favorites for insert
  with check ( auth.uid() = user_id );

-- Allow users to view their own favorites
create policy "Users can view their own favorites"
  on favorites for select
  using ( auth.uid() = user_id );

-- Allow users to delete their own favorites
create policy "Users can delete their own favorites"
  on favorites for delete
  using ( auth.uid() = user_id );
