
-- 1. جدول الاتفاقيات (Treaties)
create table if not exists treaties (
  id bigint generated by default as identity primary key,
  name text not null,
  date text,
  topic text,
  states text,
  link text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. جدول القضايا (Cases)
create table if not exists cases (
  id bigint generated by default as identity primary key,
  name text not null,
  year text,
  court text,
  summary text,
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. تفعيل الحماية
alter table treaties enable row level security;
alter table cases enable row level security;

-- 4. سياسات الأمان (Policies)
-- السماح للجميع بالقراءة (Public Read)
create policy "Public read treaties" on treaties for select using ( true );
create policy "Public read cases" on cases for select using ( true );

-- السماح للمسؤولين فقط بالإضافة والتعديل (سنسمح للمسجلين حالياً للتسريع)
create policy "Auth insert treaties" on treaties for insert with check ( auth.role() = 'authenticated' );
create policy "Auth update treaties" on treaties for update using ( auth.role() = 'authenticated' );
create policy "Auth insert cases" on cases for insert with check ( auth.role() = 'authenticated' );
create policy "Auth update cases" on cases for update using ( auth.role() = 'authenticated' );
