
-- تخزين قرارات دولية (Resolutions)
create table if not exists resolutions (
  id bigint generated by default as identity primary key,
  number text not null,
  title text,
  year text,
  subject text,
  type text, -- 'مجلس الأمن' or 'الجمعية العامة'
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- سياسات الأمان
alter table resolutions enable row level security;

create policy "Public read resolutions" on resolutions for select using ( true );
create policy "Auth insert resolutions" on resolutions for insert with check ( auth.role() = 'authenticated' );
create policy "Auth update resolutions" on resolutions for update using ( auth.role() = 'authenticated' );
